import { ProjectBlueprint, ProjectIdea, ProjectRoadmap } from '../types';

export function exportProjectAsMarkdown(
  project: ProjectIdea,
  blueprint?: ProjectBlueprint | null,
  roadmap?: ProjectRoadmap | null
): string {
  let md = `# ${project.title}\n\n`;
  md += `**Evaluation Fit Score**: ${project.fitScores?.overallFit || 'N/A'}% | **Difficulty**: ${project.difficulty} | **Timeline**: ${project.estimatedDuration}\n\n`;
  md += `## 1. Overview & Problem Statement\n\n${project.problemStatement}\n\n`;
  md += `### Real-World Use Case\n${project.realWorldUseCase}\n\n`;

  md += `## 2. Core Features\n`;
  (project.coreFeatures || []).forEach((feat, idx) => {
    md += `${idx + 1}. ${feat}\n`;
  });
  md += `\n`;

  md += `## 3. Technology Stack\n`;
  md += `- **Frontend**: ${(project.recommendedTechStack?.frontend || []).join(', ')}\n`;
  md += `- **Backend**: ${(project.recommendedTechStack?.backend || []).join(', ')}\n`;
  md += `- **Database**: ${(project.recommendedTechStack?.database || []).join(', ')}\n`;
  md += `- **AI / ML**: ${(project.recommendedTechStack?.aiOrMl || []).join(', ')}\n`;
  md += `- **DevOps / Cloud**: ${(project.recommendedTechStack?.cloudOrDevOps || []).join(', ')}\n\n`;

  md += `## 4. AI Component\n${project.aiComponent}\n\n`;

  if (blueprint) {
    md += `## 5. Architectural Blueprint\n\n`;
    md += `### System Architecture\n${blueprint.systemArchitecture}\n\n`;
    md += `### Functional Requirements\n`;
    (blueprint.functionalRequirements || []).forEach(req => {
      md += `- ${req}\n`;
    });
    md += `\n### Database Design\n`;
    (blueprint.databaseDesign || []).forEach(entity => {
      md += `#### ${entity.name}\n${entity.description}\n`;
      (entity.fields || []).forEach(f => {
        md += `  - \`${f.name}\` (${f.type}): ${f.description}\n`;
      });
    });
    md += `\n### Testing Strategy\n`;
    (blueprint.testingStrategy || []).forEach(strat => {
      md += `- ${strat}\n`;
    });
    md += `\n`;
  }

  if (roadmap) {
    md += `## 6. Development Roadmap\n\n`;
    (roadmap.phases || []).forEach(phase => {
      md += `### Phase ${phase.phaseNumber}: ${phase.title} (${phase.estimatedDuration})\n`;
      md += `*Objective*: ${phase.objective}\n\n`;
      (phase.tasks || []).forEach(task => {
        const checkbox = task.status === 'completed' ? '[x]' : '[ ]';
        md += `- ${checkbox} **${task.title}** (${task.estimatedHours} hrs) - Status: ${task.status}\n`;
      });
      md += `\n`;
    });
  }

  md += `---\n*Generated by ProjectPilot AI — Academic Capstone Blueprint Engine*\n`;
  return md;
}

export function downloadFile(filename: string, content: string, contentType = 'text/plain'): void {
  const blob = new Blob([content], { type: contentType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
